name: Build ESPHome

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: Integrations/ESPHome/PWR-1.yaml
      name: Apollo PWR-1
